export enum ERROR_MESSAGE {
  // BASIC
  FATAL = 'FATAL',

  DUPLICATED = 'DUPLICATED',
  NOT_FOUND = 'NOT_FOUND',

  INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN',

  INVALID_CREDENTIAL = 'INVALID_CREDENTIAL',
}
