services:
  postgres:
    image: postgres:17.2
    container_name: postgres_17_2
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.4
    ports:
      - 6379:6379
    volumes:
      - /data
